import type { UiLabels } from './types';

// English fallback so the dev preview (and any race before the real `openUI`
// payload arrives from Lua) still renders readable copy instead of raw keys.
export const defaultLabels: UiLabels = {
  ui_page_title: 'Telegram System',
  ui_header_title: 'Telegraph Office',
  ui_inbox: 'Telegrams',
  ui_job_inbox: 'Job Inbox',
  ui_new_message: 'New Message',
  ui_addressbook: 'Contacts',
  ui_search_messages: 'Filter telegrams...',
  ui_search_job_messages: 'Filter job telegrams...',
  ui_clear_search: 'Clear search',
  ui_sender_label: 'Sender',
  ui_personal_sender: 'Personal',
  ui_recipient_label: 'Recipient',
  ui_recipient: 'Recipient',
  ui_recipient_placeholder: 'Citizen ID, contact or job...',
  ui_subject_label: 'Title',
  ui_subject_placeholder: 'Enter the subject...',
  ui_message_label: 'Message',
  ui_message_placeholder: 'Write your message...',
  ui_send_message: 'Send Telegram',
  ui_clear: 'Clear',
  ui_add_new_contact: 'Add Contact',
  ui_contact_name_label: 'Name',
  ui_contact_name_placeholder: 'Enter the contact name...',
  ui_contact_citizenid_label: 'PO Box No.',
  ui_contact_citizenid_placeholder: 'Enter the citizen ID...',
  ui_save_contact: 'Save Contact',
  ui_cancel: 'Cancel',
  ui_confirm_send_title: 'Confirm Telegram',
  ui_confirm_send_text: 'Are you sure you want to send this telegram?',
  ui_note_label: 'Note:',
  ui_birdpost_warning: 'Sending outside a post office will consume 1 Bird Post item from your inventory.',
  ui_cost_label: 'Cost:',
  ui_cost_warning: 'Sending this message will cost',
  ui_message_details: 'Telegram',
  ui_from_label: 'Sender',
  ui_to_label: 'Recipient',
  ui_date_label: 'Date',
  ui_reply: 'Reply',
  ui_delete: 'Delete',
  ui_close: 'Close',
  ui_empty_inbox: 'No telegrams in your inbox',
  ui_empty_job_inbox: 'No telegrams in your job inbox',
  ui_at_post_office: 'At Post Office',
  ui_job_badge: 'Job',
  ui_empty_addressbook: 'No contacts saved',
  ui_citizenid_display: 'PO Box No. {citizenid}',
  ui_remove_contact: 'Remove Contact',
  ui_reply_subject_prefix: 'Re:',
};
